### ISSUE TITLE
Fail to extract pgs to srt when multiple subtitles are rendered

### ISSUE THREAD

**Issue by javierlopeza** [wydengyre/pgs-to-srt#231]
I've came across several subtitles that fail to extract from PGS to SRT and they all share similar scenes where subtitles are rendered at the top and bottom of the screen (generally when some signs and speech have to render at the same time). 

See example below:
<img width="500" alt="Screenshot 2024-05-03 at 10 02 04 AM" src="https://github.com/wydengyre/pgs-to-srt/assets/11431769/8984a19f-d7df-4f7a-879f-d1e16810c34a">

Here is a .sup file extracted from the video that reproduces the error: [Google Drive link](https://drive.google.com/file/d/1JiHLMdPZ-rOsLuxJY8G5_nPxI_uI_7ZX/view?usp=sharing)

For this .sup file, when I run the image extraction for the 109 frame (screenshot above):
```
$ pgs-to-srt 109 "Death Note (2006) - S01E06 - 006 - Unraveling [Bluray-720p][10bit][x264][FLAC 2.0][EN+JA+E
S+FR+PT]-NoobSubs.en.sup" > image.bmp
```
The error I get is:
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Ft (file:///pgs-to-srt/pgs-to-srt.js:2:79154)
    at Lt (file:///pgs-to-srt/pgs-to-srt.js:2:81570)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///pgs-to-srt/pgs-to-srt.js:8:598
```
I also tried extracting it using [pgs-to-srt.com](pgs-to-srt.com) but the process gets stuck and the browser console shows the following error:
<img width="1733" alt="Screenshot 2024-05-03 at 10 13 31 AM" src="https://github.com/wydengyre/pgs-to-srt/assets/11431769/02350c0d-fd9e-4342-bf35-322e0eab09dc">

**Comment by wydengyre** [comment]
Thank you for the very detailed error report. I'm definitely eager to tackle this error. Really appreciate your inclusion of a link to the file, too.

I'm trying to rearchitect this whole application, so it might take me a little while. Thanks for bearing with me!
